---
# ansible-playbook hyperion.yml -t gui

- import_tasks: core/pkg.yml
  tags:
    - core

- import_tasks: gui/pkg.yml
  tags:
    - gui

- import_tasks: openstack/pkg.yml
  tags:
    - openstack

- import_tasks: microcloud/pkg.yml
  tags:
    - ovirt

- import_tasks: migrate/pkg.yml
  tags:
    - migrate
